apiVersion: v1
kind: Service
metadata:
  name: async-pull
  namespace: async-pull
  labels:
    app: async-pull
spec:
  type: LoadBalancer
  selector:
    app: async-pull
  ports:
  - port: 8080
    targetPort: http-server